### ISSUE TITLE
Dynamic schema loading

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sn-client-core#20]
# Tasks
## Sensenet Services
 - [x] Create custom OData action that returns the Schema data
 - [x] Create importable content
 - [x] Remove null values
 - [x] Testing

## @sensenet/client-core
 - [x] Extend RepositoryConfig to accept schema infos
 - [x] Add API endpoint on repository to reload schemas at runtime
 - [x] Testing
 - [x] Update docs

## @sensenet/controls-aurelia
 - [x] Update ContentView component and ControlMappingService to handle schema changes
 - [x] Deploy new release

## @sensenet/redux
 - [x] Add action for schema reloading
 - [x] Check if schemas should be placed in the Redux store as well

## @sensenet/controls-react
 - [x] Deploy new release
